name: miio
description: Dart implementation of MiIO LAN protocol for smart home devices.
version: 0.7.0
homepage: https://github.com/ctrysbita/miio.dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
  cryptography: ^2.0.0
  json_annotation: ^4.5.0
  logger: ^1.0.0
  meta: ^1.3.0
  quiver: ^3.0.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^2.0.0
